###
POST  http://localhost:4000/register/
Content-Type:application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###
POST http://localhost:4000/login/
Content-Type:application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###
GET http://localhost:4000/user/tweets/feed
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw
###
GET http://localhost:4000/user/following/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw
###
GET http://localhost:4000/user/followers/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw
###
GET http://localhost:4000/tweets/4/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw
###
GET http://localhost:4000/tweets/4/likes
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw
###
GET http://localhost:4000/tweets/4/replies
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw
###
GET http://localhost:4000/user/tweets
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw
###
POST http://localhost:4000/user/tweets
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw

{
   "tweet": "The Mornings..."
}
###
DELETE http://localhost:4000/tweets/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2OTAyNzE1fQ.Jx6wIDOSoZhL_lHzGT4iDu9m7eKPGQYYGmDnotuPdEw

